FROM rust:1-bookworm

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN cargo install sqlx-cli --no-default-features --features postgres

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY migrations ./migrations

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build && cp target/debug/basegame-api /app/basegame-api

EXPOSE 80

CMD ["sh", "-c", "exec ./basegame-api"]

# FROM rust:1-bookworm AS builder
#
# WORKDIR /app
#
# RUN apt-get update && apt-get install -y pkg-config libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
#
# COPY Cargo.toml Cargo.lock ./
# COPY src ./src
# COPY migrations ./migrations
#
# RUN --mount=type=cache,target=/usr/local/cargo/registry \
#     --mount=type=cache,target=/app/target \
#     cargo build --release --locked && \
#     cp /app/target/release/basegame-api /app/basegame-api
#
# FROM debian:bookworm-slim
#
# WORKDIR /app
#
# RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
#
# COPY --from=builder /app/basegame-api /app/basegame-api
# COPY --from=builder /app/migrations /app/migrations
#
# EXPOSE 8080
#
# CMD ["./basegame-api"]
